### ISSUE TITLE
Add support for externally tagged unions

### ISSUE THREAD

**Issue by sphinxc0re** [Aleph-Alpha/ts-rs#10]
`Externally tagged unions` it the default for serde enums in e.g. JSON.
 
An enum like this:

```rust
pub enum Field {
    Floor,
    Wall,
    Portal { id: usize, target: MapAddress },
    Exit,
    Special { id: usize },
}
```

would convert to this:

```typescript
export type Field =
  | "Floor"
  | "Wall"
  | {
      Portal: {
        id: number;
        target: MapAddress;
      };
    }
  | "Exit"
  | {
      Special: {
        id: number;
      };
    };
```

It looks kinda ugly but it's very useful to me and it's the serde default.

**Comment by NyxCode** [comment]
I have thought about this, and I do agree!
The default serde behavious looks disgusting, but we need to be compatible to it.
I've created [this new branch](https://github.com/Aleph-Alpha/ts-rs/tree/enums-serde-compat) to make this the default behaviour.

**Comment by NyxCode** [comment]
closing in favor of #38
