### ISSUE TITLE
How to generate bindings without running test?

### ISSUE THREAD

**Issue by yujong-lee** [Aleph-Alpha/ts-rs#106]
https://github.com/Aleph-Alpha/ts-rs/blob/147e1522763596ad17508d62e57c1062c575948e/README.md?plain=1#L39

I know I can generate bindings with `cargo test`. But I want a way to only generate bindings without running tests.

Can you guide me to achieve this please?

Thank you.

**Comment by NyxCode** [comment]
Hey @yujong-lee,
you can omit the `#[ts(export)]` attribute, and call `TS::export` on your type yourself.  
This is documented [here](https://docs.rs/ts-rs/latest/ts_rs/trait.TS.html#exporting)

**Comment by yujong-lee** [comment]
@NyxCode  Sorry that I ask you again that is already documented. Thanks for your response.
