### ISSUE TITLE
Serde warning on #[ts(skip)] attribute

### ISSUE THREAD

**Issue by ThibaudDauce** [Aleph-Alpha/ts-rs#107]
I have a struct with a default function for serde:

```rust
#[derive(Debug, Clone, Deserialize, Serialize, TS)]
#[ts(export)]
pub struct Foobar {
    #[ts(skip)]
    #[serde(skip, default = "default_http_version")]
    pub http_version: Version,
    …
}
```

I got a warning that ts-rs cannot parse the serde attribute (which is working with Serde alone):

```
warning: failed to parse serde attribute
  | 
  | #[serde(skip, default = "default_enclave_http_version")]
  | 
  = note: ts-rs failed to parse this attribute. It will be ignored.
```

The main problem is not the failed to parse serde attribute (the default value is a Rust function so I'm not sure TypeScript can understand that) but that the warning is still emitted with the `#[ts(skip)]` annotation.

**Comment by NyxCode** [comment]
This should be fixed on latest master - when encountering a #[ts(skip)] attribute, serde attributes are now just ignored.
