### ISSUE TITLE
generating invalid TypeScript import path with using Cargo workspace

### ISSUE THREAD

**Issue by h-michael** [Aleph-Alpha/ts-rs#111]
Hi, thanks for your excellent work. I love ts-rs.

I use ts-rs with the project which uses Carog workspace. I found the following issue.
If that project has crates on both the grandchildren directory and child directory, it may generate an invalid TypeScript import path.
I created [example project](https://github.com/h-michael/ts-rs-cargo-workspace-example).
[This struct](https://github.com/h-michael/ts-rs-cargo-workspace-example/blob/3b0b675606fc8e4cfc1e6d693a7f78310e7cb0a4/api/src/lib.rs#L1-L13) uses another [crate's struct](https://github.com/h-michael/ts-rs-cargo-workspace-example/blob/3b0b675606fc8e4cfc1e6d693a7f78310e7cb0a4/dep_a/lib_a/src/lib.rs#L3-L8) that crates on the grandchildren directory.
In this case, [invalid import paths](https://github.com/h-michael/ts-rs-cargo-workspace-example/blob/3b0b675606fc8e4cfc1e6d693a7f78310e7cb0a4/bindings/ABC.ts#L2-L3) are generated.
That should be as follows.

```typescript
import type { A } from "./A";
import type { B } from "./B";
```

I know this is a corner case. I can avoid this by using a flattened directory architecture. But actually, I use ts-rs with a bigger mono repository than the above example. So I want to use nested directories to categorize crates.

If you can give me some guidelines to fix this problem, I can create PR to fix it. Thanks.

**Comment by escritorio-gustavo** [comment]
Fixed by #221 and #218
