### ISSUE TITLE
How to use `ts-rs` with `tauri dev`?

### ISSUE THREAD

**Issue by sasial-dev** [Aleph-Alpha/ts-rs#130]
I'm creating a [tauri app](https://tauri.app). When I run `tauri dev`, it essentially runs the rust code compiling & reloading on save. In this case, as compiles and runs, so the TS types may not be up to date.
Is there an alternative to using the test macros?

**Comment by sasial-dev** [comment]
Running `::export()` in `build.rs`!

**Comment by sasial-dev** [comment]
It isn't in the public API, I created a crate under a workspace, and went through each type struct running `::export`
```rs
use ts_rs::{TS, ExportError};

pub mod prelude;
pub mod error;
pub mod utils;

pub mod event;
pub mod model;
pub mod store;

pub fn export_ts_types() -> Result<(), ExportError> {
    // if a type has generics:
    <event::HubEvent<()> as TS>::export()?; // we must type assert here to get around the generic issue...

    model::ModelMutateResultData::export()?;
    model::project::Project::export()?;
    model::project::ProjectForCreate::export()?;
    model::project::ProjectForUpdate::export()?;

    Ok(())
}
```

**Comment by 8ctopotamus** [comment]
Not sure if this is a legit solution, but I just added `cargo test` to the `beforeBuildCommand` and `beforeDevCommand` in the `tauri.conf.json`.

```json
"build": {
    "beforeBuildCommand": "cargo test && npm run build",
    "beforeDevCommand": "cargo test && npm run dev",
    "devPath": "http://localhost:5173",
    "distDir": "../build"
  }
```
