### ISSUE TITLE
Use `{ [key: K]: V }` instead or `Record<K, V>` for Maps

### ISSUE THREAD

**Issue by ramiroaisen** [Aleph-Alpha/ts-rs#134]
If we use 

```typescript
type T = Record<K, V>
```
and `V` is a type that circular reference type `T` we get an error in typescript.

This doesn't happen with 

```typescript
type T = { [key: K]: V }
``` 

If you are ok with this change I can make a PR, is a simple two liner change.

**Comment by carlocorradini** [comment]
Off topic: How about enabling also [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)?

```ts
import type { B } from "./B";

export type A {
  map: Map<string, B>
}
```

**Comment by escritorio-gustavo** [comment]
> and V is a type that circular reference type T we get an error in typescript.

Hey @ramiroaisen! Can you give an example of this for testing?

**Comment by escritorio-gustavo** [comment]
> Off topic: How about enabling also [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)?

I don't think support for Map will be implemented, but you can use `#[type = "Map<K, V>"]`

**Comment by escritorio-gustavo** [comment]
This issue seems to be stale, so I'll close it for now. If there is still interest in this feature, please open a new issue.

**Comment by escritorio-gustavo** [comment]
Due to #276, this has become a relevant issue for new features, so I'm reopening the issue
