### ISSUE TITLE
Generate types on build

### ISSUE THREAD

**Issue by boul2gom** [Aleph-Alpha/ts-rs#166]
Hi 👋
There is a way to generate types on build, or when wanted, through build.rs please ? Because actually, the only way is to call `cargo test` in build.rs, ans its run every tests, including integration testing. Maybe a `ts_rs::export_types()`` can be useful to call, instead of using tests.
Thanks a lot

**Comment by dessalines** [comment]
`cargo test export_bindings` should be added to the readme as the main way to generate these bindings. Lots of projects have tests that can take a long time to run, and it was hard to find this answer.
