### ISSUE TITLE
Make `Option` different in the struct 

### ISSUE THREAD

**Issue by xiao-e-yun** [Aleph-Alpha/ts-rs#167]
Is it possible?
```rs
pub struct A {
  b: u8,
  c: Option<u8>
}
```
expect
```ts
export interface A {
  b: number,
  c: number | null | undefined,
  //Or like this if in struct
  c?: number 
}
```

**Comment by escritorio-gustavo** [comment]
I think it may be possible, but since serde converts `None` to `null`, I don't think it would behave as you expect

**Comment by escritorio-gustavo** [comment]
This should do what you want
```rs
pub struct A {
  b: u8,
  #[ts(optional)]
  c: Option<u8>
}
```

**Comment by joaohcopetti** [comment]
> This should do what you want
> 
> #[derive(ts_rs::TS)]
> pub struct A {
>   b: u8,
>   #[ts(optional)]
>   c: Option<u8>
> }

Is there any way to make all fields automatically like that? It's not viable to set this attribute for every optional field.

**Comment by gustavo-shigueo** [comment]
Hey @JohnHammerSky, yes there is

```rs
#[derive(TS)]
#[ts(optional_fields)]
struct Foo {
  a: Option<i32>,
  b: Option<String>
  c: i32
}
````

This will emit
```ts
type Foo = {
  a?: number
  b?: string
  c: number
}
```

**Comment by joaohcopetti** [comment]
@gustavo-shigueo Thank you, it worked.

I think you're missing `export` tho, it didn't work without export for me, so it became:
```rust
#[ts(export, optional_fields)]
```
