### ISSUE TITLE
Include `ObjectId` from `mongodb`

### ISSUE THREAD

**Issue by bennyhodl** [Aleph-Alpha/ts-rs#186]
When I generate bindings with the `bson` feature it does not include the import in the generated files.

How can I get it to auto import?

**Comment by escritorio-gustavo** [comment]
Hey @bennyhodl, there have been a lot of changes to the import logic recently, can you try in the current `main` and, if, the issue persists, send us a minimal reproduction?

**Comment by escritorio-gustavo** [comment]
Closing this until a minimal repro is submitted
