### ISSUE TITLE
Export `enum` instead of `type` for simple C-like enums

### ISSUE THREAD

**Issue by JakubKoralewski** [Aleph-Alpha/ts-rs#23]
When Rust's enums could be represented with TypeScript's enums I think they should. So for example an enum like:

```rs
#[derive(serde::Serialize, ts_rs::TS)
enum Color {
	#[serde(rename="R")
	Red,
	Blue,
	Green
}
```

should end up as

```ts
export enum Color {
	Red="R",
	Blue,
	Green
}
```

Maybe even `const enum`? Should probably be optional with an attribute on the enum.

Instead of currently it being: `export type Color = "R" | "Blue" | "Green"`;

**Comment by JakubKoralewski** [comment]
> Probably const enums might work well,

Yes they should nullify your case about memory usage.

> I am unsure if they have some other significant downsides, which makes sense to consider.

I've had some issues with sharing const enums across projects, can't recall the details.

My thought process is: let's make it possible to do this.

> When you use enum you actually generate code

Maybe that's what the user wants. You can achieve some nice behavior by indexing into the enum object, or iterating through all the keys etc.

**Comment by NyxCode** [comment]
I do agree that having the option to generate one or the other is better than not having it.  
I think we need a way to configure the macro not only through attributes, but also through a config file which applies to all invocations. This is currently really tricky because of incremental compilation, but I'll take a look at it. If anyone wants to give that ago, please do!

**Comment by barel-mishal** [comment]
Hi, it seems I encountered a similar issue. However, after reading the discussion here, I've realized that it might be more cost-effective to eliminate my use of enums in my code. I'm uncertain about the necessity of supporting enums in JavaScript/TypeScript.

That said, I'd like to provide some context. In my project, I've been using a lot of enums. Lately, I've been transitioning to Rust to benefit from better maintainability, fewer bugs, and a superior testing environment. This led me to the project "ts-rs", which I personally appreciate and use extensively. Occasionally, I wish it had better compatibility with serde when I utilize types from other crates.

Regarding enums, while I don't believe "ts-rs" needs to support JavaScript enums, it should offer documentation and links to relevant discussions. After discovering this discussion, I began transitioning my enums to types using "ts-rs". I must say the results have been promising with less code to manage and similar logic to before, with only a few changes.

```typescript
// using types from ts-rs
export const getFeedBackText = (
    feedback: Feedback
  ) => {
    switch (feedback) {
 
      case 'SignificantlyBelowRange':
        return `הצריכה שלך של ${nutriHebrew} היא ${intake} ${nutriUnitHebrew}, הרבה מתחת לטווח המומלץ של ${bounds.min} עד ${bounds.max} ${nutriUnitHebrew}. חשוב מאוד לוודא שאתה מקבל מספיק ${nutriUnitHebrew} מהתזונה שלך לבריאותך.`;
  
      case 'SlightlyBelowRange':
        return `הצריכה שלך של ${nutriHebrew} היא ${intake} ${nutriUnitHebrew}, קצת מתחת לטווח המומלץ של ${bounds.min} עד ${bounds.max} ${nutriUnitHebrew}. שקול להגביר את הצריכה שלך כדי להגיע לרמות המומלצות.`;
  
      case 'WithinRange':
        return `הצריכה שלך של ${nutriHebrew} היא ${intake} ${nutriUnitHebrew}, בטווח המומלץ של ${bounds.min} עד ${bounds.max} ${nutriUnitHebrew}. עבודה טובה, המשך כך!`;
  
      case 'SlightlyAboveRange':
        return `הצריכה שלך של ${nutriHebrew} היא ${intake} ${nutriUnitHebrew}, קצת מעל לטווח המומלץ של ${bounds.min} עד ${bounds.max} ${nutriUnitHebrew}. עקוב אחר הצריכה שלך כדי לוודא שהיא ברמה האופטימלית לבריאותך.`;
  
      case 'SignificantlyAboveRange':
        return `הצריכה שלך של ${nutriHebrew} היא ${intake} ${nutriUnitHebrew}, הרבה מעל לטווח המומלץ של ${bounds.min} עד ${bounds.max} ${nutriUnitHebrew}. שקול לבצע התאמות בתזונה שלך לתוצאות בריאות טובות יותר.`;
  
    }
  
  }
  // using enum!
  export const getFeedBackText = (
    feedback: Feedback, 
  ) => {
  
    switch (feedback) {
  
      case Feedback.SignificantlyBelowRange:
        return `some text...`;
  
      case Feedback.SlightlyBelowRange:
        return `some text...`;
  
      case Feedback.WithinRange:
        return `some text...`;
  
      case Feedback.SlightlyAboveRange:
        return `some text...`;
  
      case Feedback.SignificantlyAboveRange:
        return `some text...`;
    }
  }
  ```
As you can observe, the code has barely changed and retains its previous types. Another example demonstrates using a function to return an enum type.
```typescript
// using types from ts-rs
export const getFeedback = (intake: number, range: AdjustedBounds): Feedback => {
    if (intake < range.lowerBound) return 'SignificantlyBelowRange';
    if (intake < range.min) return 'SlightlyBelowRange';
    if (intake >= range.min && intake <= range.max) return 'WithinRange';
    if (intake > range.max && intake <= range.upperBound) return 'SlightlyAboveRange';
    return 'SignificantlyAboveRange';
}

// using enum
export const getFeedback = (value: number, range: AdjustedBounds) => {
    if (value < range.lowerBound) return Feedback.SignificantlyBelowRange;
    if (value < range.min) return Feedback.SlightlyBelowRange;
    if (value >= range.min && value <= range.max) return Feedback.WithinRange;
    if (value > range.max && value <= range.upperBound) return Feedback.SlightlyAboveRange;
    return Feedback.SignificantlyAboveRange;
}
```
In the second example, I explicitly returned the type of Feedback to ensure consistent type accuracy. This was the primary logic difference necessary to maintain the same type safety for this use case.

I hope to see improved documentation and more insights on handling unsupported types. While this topic is mentioned, I find it to be a frequent and challenging issue for newcomers wanting to integrate this project into their workflow.

Thank you for creating this project!

**Comment by hpapier** [comment]
Hi :)

While I think reconsidering the use cases of enums in Typescript is good (leading to stronger typing, less code generation, etc), it still has some main benefits, the main one I see so far is the fact that an enum serves also as a constant of values, that you can iterate over. It is then used to type and to centralise information. For me both cases should be covered, transforming enums to types or to plain JS enums.

Thank you for the project! :)

**Comment by escritorio-gustavo** [comment]
TS enums are generally considered to be really bad and serde doesnt really support any conversions that would make them easy to use out of the box (though it can probably be done with `serde-repr`). In general type unions, wether it is a union of strings or a discriminated union are the preferred way to go, so I don't think support for TS enums is planned for this crate. We have been working on improving the use of Rust enums by allowing them to be `flatten`ed but I think that's all we will be doing in regards to enums.

Would like @NyxCode to confirm this first, but I'm leaning towards closing this as not planned

**Comment by escritorio-gustavo** [comment]
If this feature is really something people need, please make a PR after #206 is merged

**Comment by NyxCode** [comment]
Agreed, let's close this for now. If there ends up being lots of interest in the feature, we should probably do some refactorings first, especially because I'm not sure how it'd interact with enum flattening.

**Comment by setoelkahfi** [comment]
@NyxCode Could we reconsider this? I found a closed issue and I explained my case there https://github.com/Aleph-Alpha/ts-rs/issues/140.

**Comment by MrAliSalehi** [comment]
same case here, need to use enums for "some" parts of the code,
i think an optional feature would be great for this

**Comment by Nutomic** [comment]
We need this in order to check that a translation string is defined for each enum variant. So please reopen the issue.

**Comment by Nutomic** [comment]
@rail-ka That would work, but as the enum has around 100 items it would get extremely verbose to write everything out. For comparison with an enum its as easy like this:
```typescript
enum Errors {
  WrongPassword,
  InvalidEmail,
  // etc
}

for (let item in Errors) {
  if (isNaN(Number(item))) {
      check_translation_exists(item);
  }
}
```
