### ISSUE TITLE
Bug: `#[ts(skip)]` does not work properly in newtype variants of adjacently or internally tagged enums

### ISSUE THREAD

**Issue by timephy** [Aleph-Alpha/ts-rs#230]
## Explanation

As the title says, the (new) implementation for `TypeList` uses the type of `skip`ped fields for type dependencies.
This requires those types to implement `TS`, which some do not (like `anyhow::Error`, see image below).

This happens to me when using the feature implemented in #180.

Errors:
- "the trait bound `anyhow::Error: TS` is not satisfied"
- "the method `extend` exists for associated type `impl TypeList`, but its trait bounds were not satisfied"
<img width="527" alt="image" src="https://github.com/Aleph-Alpha/ts-rs/assets/28571656/45c88ed0-12b2-4c86-a56b-b144f5a449f2">

## Expectation

`TypeList` skips the type of `skip`ped fields.

## Context

I'd like to update the version used in one of my projects to the current version of the `main` branch with the new `doc` support on types, but this breaks dozens of my error-types (as seen in the image above).

**Comment by NyxCode** [comment]
Are you sure that you're compiling with the `serde-compat` feature enabled? If not, then the `#[serde(...)]` attributes have no effect.

**Comment by NyxCode** [comment]
Ah, okay, seems like you found a regression!
I suspect it wasn't introduced with `TypeList`, but together with the rework of enums.

This here works
```rust
struct Unsupported;

#[derive(TS, Serialize)]
enum X {
    A (
        #[serde(skip)]
        Unsupported
    ),
}
```

But adding `#[serde(tag = "t")]` doesn't:
```rust
struct Unsupported;

#[derive(TS, Serialize)]
#[serde(tag = "t")]
enum X {
    A (
        #[serde(skip)]
        Unsupported
    ),
}
```
```
error[E0277]: the trait bound `Unsupported: TS` is not satisfied  
```
