### ISSUE TITLE
Feature request: `#[ts(bound)]` attribute

### ISSUE THREAD

**Issue by WilsonGramer** [Aleph-Alpha/ts-rs#268]
**Is your feature request related to a problem? Please describe.**
#264 introduces the `#[ts(concrete)]` attribute, but it can generate unnecessary bounds on the type parameter when it's used "directly" in a type:

```rust
use ts_rs::TS;

trait Driver {
    type Info: TS;
}

struct TsDriver;

#[derive(TS)]
struct TsInfo;

impl Driver for TsDriver {
    type Info = TsInfo;
}

#[derive(TS)]
#[ts(export, concrete(D = TsDriver))]
struct Inner<D: Driver> {
    info: D::Info,
}

#[derive(TS)]
#[ts(export, concrete(D = TsDriver))]
struct Outer<D: Driver> {
    inner: Inner<D>,
}
```

```
error[E0277]: the trait bound `TsDriver: ts_rs::TS` is not satisfied
   --> src/lib.rs:22:10
    |
22  | #[derive(TS)]
    |          ^^ the trait `ts_rs::TS` is not implemented for `TsDriver`
    |
    = help: the following other types implement trait `ts_rs::TS`:
              bool
              char
              isize
              i8
              i16
              i32
              i64
              i128
            and 66 others
note: required for `Outer<TsDriver>` to implement `ts_rs::TS`
   --> src/lib.rs:22:10
    |
22  | #[derive(TS)]
    |          ^^ unsatisfied trait bound introduced in this `derive` macro
note: required by a bound in `ts_rs::TS::WithoutGenerics`
   --> /Users/wilson/.cargo/git/checkouts/ts-rs-092fe627e6f08b9c/95e6dac/ts-rs/src/lib.rs:332:27
    |
332 |     type WithoutGenerics: TS + ?Sized;
    |                           ^^ required by this bound in `TS::WithoutGenerics`
    = note: this error originates in the derive macro `TS` (in Nightly builds, run with -Z macro-backtrace for more info)
```

ts-rs thinks that a value of type `D` is used in `Outer` because it's passed as a parameter to `Inner`, when in reality `Inner` only uses `D::Info`. The generated code looks like this:

```rust
impl<D: Driver> ts_rs::TS for Outer<D>
where
    D: ts_rs::TS, // <- unnecessary bound
{
    ...
}
```

**Describe the solution you'd like**
Add a `#[ts(bound)]` attribute to let people specify the bounds on the `TS` impl manually:

```rust
#[derive(TS)]
#[ts(export, concrete(D = TsDriver), bound = "D::Info: TS")]
struct Outer<D: Driver> {
    inner: Inner<D>,
}
```

Which would replace the auto-generated bounds with the provided string:

```rust
impl<D: Driver> ts_rs::TS for Outer<D>
where D::Info: TS,
{
    ...
}
```

**Describe alternatives you've considered**
See #261 and #264.

**Comment by WilsonGramer** [comment]
@NyxCode You're right, I meant to write this:

```rust
impl ts_rs::TS for Outer<TsDriver>
where /* no bounds */
{
    ...
}
```

...because `D` is substituted for `TsDriver` with `#[ts(concrete(D = TsDriver), bound = "/* no bounds */"]`. You're right that without `concrete`, the bound would be needed. I might be missing something though.

**Comment by NyxCode** [comment]
Ah, alright, now I see where the confusion came from.

So the original `concrete` branch started out with `impl<D: Driver> TS for MyStruct<D>`.  
That worked, but required this annoying `type Info: TS` bound in the definition of `Driver`.

Then, we tried actually generating `impl TS for MyStruct<TsDriver>`. However, we hit a hard wall going down that road. If you're interested in the details, see #264. The gist of it is that we generated `<TsDriver::Info as TS>::name()` inside the `impl`, which the trait solver refuses to accept. We'd have to generate `<<TsDriver as Driver>::Info as TS>::name()` instead, but that's not possible inside the proc macro (as soon as there's more than one trait bound on `D`). 

Therefore, we settled on generating `impl<D: Driver> TS for MyStruct<D> where D::Info: TS`. That gives us all the benifits we'd have gotten with the other approach (namely, get rid of the `type Info: TS` bound).

Everything works like it was an `impl TS for MyStruct<TsDriver>`. However, `MyStruct<OtherDriver>` still implements `TS` if `OtherDriver::Info: TS`. If you'd call `MyStruct<OtherDriver>::decl()` though, it'll behave as-if it was an `MyStruct<TsDriver>`.

**Comment by NyxCode** [comment]
Absolutely, that'd have worked! With the codegen as-is, which does `<{field_type} as TS>::name()`, that'd have generated `<<D as Driver>::Info as TS>::name()` - exactly what we tried to do "by hand".  

We didn't see any downside with generating `impl<D: Driver> TS for MyStruct<D> where D::Info`, and it doesn't require that you touch the type definition at all.

**Comment by NyxCode** [comment]
Well, there is one downside, which is that you don't get a compiler error if you do `MyStruct::<OtherDriver>::export()` if it's `#[ts(concrete(D = TsDriver))]`. Instead, you just get the definition of `MyStruct<TsDriver>` according to the `#[ts(concrete(..)]`.

Since (we hope) most users just use `#[ts(export)]`, this seemed like a minor issue.

**Comment by WilsonGramer** [comment]
@NyxCode Got it! I just tested the latest changes on main, but I'm still getting the extra bound when I `#[derive(TS)]` on `Outer`:

```rust
use ts_rs::TS;

trait Driver {
    type Info: TS;
}

struct MyDriver;

#[derive(TS)]
struct MyInfo;

impl Driver for MyDriver {
    type Info = MyInfo;
}

#[derive(TS)]
#[ts(export, concrete(D = MyDriver))]
struct Inner<D: Driver> {
    info: D::Info,
}

#[derive(TS)]
#[ts(export, concrete(D = MyDriver))]
struct Outer<D: Driver> {
    inner: Inner<D>,
}
```

```diff
  impl<D: Driver> ::ts_rs::TS for Outer<D>
  where
+     D: ::ts_rs::TS,
  {
      ...
  }
```

Basically, the current implementation requires `MyDriver` itself implements `TS`, not just its associated types, since it sees that `D` is used "directly" in `Outer` — the goal with `#[ts(bound = "")]` is to remove this bound (since it's not actually necessary that `D` itself implements `TS`, only its associated types).

**Comment by NyxCode** [comment]
Yup, we're on the same page here!

The tradeoff between the two solutions of generating trait bounds we explored turned out to be:
- Generate perfect bounds, but fail on self-referential types
- Overestimate bounds, but allow self-referential types

So you're absolutely right here - The generated bound `D: TS` is wrong, and it needs to be `D::Info: TS` instead. 
And I agree, `#[ts(bound = "...")]` seems perfect for that.

**Comment by WilsonGramer** [comment]
OK great! I am putting together a `bound` attribute now and will open a PR soon.

**Comment by WilsonGramer** [comment]
I just implemented the attribute here: https://github.com/Aleph-Alpha/ts-rs/compare/main...WilsonGramer:ts-rs:bound-attribute

Let me know what you think!
