### ISSUE TITLE
support for chrono NaiveDateTime?

### ISSUE THREAD

**Issue by Niedzwiedzw** [Aleph-Alpha/ts-rs#28]
I'm getting an error when using with a struct with `NaiveDateTime` field, how would I go about that?

**Comment by NyxCode** [comment]
You'd want to enable the `chrono-impl` feature. Then, it should just work. If it doesn't, make sure you're on the latest version

**Comment by NyxCode** [comment]
Version 4.0 includes proper support for all types from chrono.
Just for the record: If there are types which aren't supported, you can always add an override: `#[ts(type = "string")]`

**Comment by Mattchine** [comment]
Should it be typescript of type `string` or `Date`?
Currently `ts-rs` convert rust chrono `date` into typescript `string`.

But of course, I should just explicitly add `#[ts(type = "Date")]`.

Thanks for such a nice work anyway :))
