### ISSUE TITLE
Add all of `ts(function)` to docs.

### ISSUE THREAD

**Issue by xiao-e-yun** [Aleph-Alpha/ts-rs#327]
It is hard to know what functions i can use.
`ts(optional)` even not show on examples and docs.

**Comment by NyxCode** [comment]
[docs](https://docs.rs/ts-rs/latest/ts_rs/trait.TS.html)
[tests, if the example is not enough](https://github.com/Aleph-Alpha/ts-rs/tree/main/ts-rs/tests/integration)
If you want to extend the example, feel free to open a PR.

**Comment by escritorio-gustavo** [comment]
Also, if you use an invalid `#[ts(non_sense)]` attribute, the compiler error will tell you what the valid attributes are in the current context
