### ISSUE TITLE
publish release please 

### ISSUE THREAD

**Issue by jessfraz** [Aleph-Alpha/ts-rs#330]
Hi!

Thank you so much for your project we really appreciate it. Also you should set up sponsors so we can sponsor you :)

Was wondering if you could publish a release, we need commit https://github.com/Aleph-Alpha/ts-rs/commit/c5109a00e4a4feb7b614d35ddca2590300bdfb67 in a release, so we can publish our library to cargo. Thank you so much!

**Comment by jessfraz** [comment]
HERO!

**Comment by gustavo-shigueo** [comment]
That would be @NyxCode, I just close the issue xD

**Comment by NyxCode** [comment]
Hey @jessfraz!
Thank you, that's wonderful to hear!  

I have set up a sponsor page. Been planning to do so for a while now, but I finally got around to it. Besides financially supporting me or @gustavo-shigueo, we also always welcome direct contributions.  

I created ts-rs while working for Aleph-Alpha, but I do not work there anymore. My contributions happen in my free time, whenever I have some to spare.

**Comment by gustavo-shigueo** [comment]
> Also you should set up sponsors so we can sponsor you :)

> I have set up a sponsor page. Been planning to do so for a while now, but I finally got around to it. 

I have just recently set one up too, though I heavily encourage sponsoring @NyxCode instead

> Besides financially supporting me or @gustavo-shigueo

I would also love a job indication 😅

**Comment by jessfraz** [comment]
Done :)
