### ISSUE TITLE
Use std::path::absolute

### ISSUE THREAD

**Issue by NyxCode** [Aleph-Alpha/ts-rs#332]
`std::path::absolute` [got stabilized in 1.79.0](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html#stabilized-apis)

**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Use the stdlib's `std::path::absolute`

**TODOs**
- [ ] figure out if we want to do that right away, or wait a bit until 1.79.0 is widely adopted
- [ ] make sure our path::absolute does 1:1 the same thing

**Comment by gustavo-shigueo** [comment]
They've stabilized it?! Awesome! This will help remove the duplicate we have in the cli branch. Though it is another *technically* a breaking change due to raising the MSRV

**Comment by gustavo-shigueo** [comment]
> * make sure our path::absolute does 1:1 the same thing

I'll create a PR applying the change to see if CI passes

**Comment by gustavo-shigueo** [comment]
`std::path::absolute` does not resolve `..` path components, and therefore does not maintain the behavior we need
