### ISSUE TITLE
cannot find uuid-impl feature.

### ISSUE THREAD

**Issue by boan-anbo** [Aleph-Alpha/ts-rs#34]
`ts-rs = {version = "4", features = ["chrono-impl", "uuid-impl"]}`

And it says, 
```
depends on `ts-rs`, with features: `uuid-impl` but `ts-rs` does not have these features.
```

the chorono-impl is working alright by itself.

**Comment by boan-anbo** [comment]
got it working for now by overriding with string annotation.

**Comment by NyxCode** [comment]
Yeah, the uuid feature just got added and is not yet published to crates.io
`#[ts(type = "string")]` is the way to go until it's published.
