### ISSUE TITLE
bug: complex nested (and flattened) enum type produces invalid syntax

### ISSUE THREAD

**Issue by michaelhthomas** [Aleph-Alpha/ts-rs#343]
**Describe the bug**
Generating types for the `InputField` type in the reproduction below produces typescript with invalid syntax (a superfluous curly brace). My guess is that this has to do with the nested flattening of enums.

**To Reproduce**
1. Clone the reproduction repository: https://github.com/michaelhthomas/tsrs_repr
2. Run `cargo test`
3. Open the file `bindings/InputField.ts`
4. See syntax error due to extra `}` at end of file

**Expected behavior**
There are no syntax errors in the generated typescript code.

**Screenshots**
<img width="1469" alt="Image displaying syntax error in IDE" src="https://github.com/user-attachments/assets/6db3fd6b-9d2e-48d8-8ee1-2e2f9c88f14b">

**Version**
9.0.1

**Additional context**

**Comment by gustavo-shigueo** [comment]
Hi @michaelhthomas, thanks for the report and especially for providing a reproduction!

I've opend a PR to fix this issue, check out #344
