### ISSUE TITLE
Dependency paths in Windows use back slash, though they should use the canonical forward slash

### ISSUE THREAD

**Issue by abhay-agarwal** [Aleph-Alpha/ts-rs#345]
On windows, generated definitions are created with backslashes as opposed to forward slashes:

```ts
import type { MyType } from "..\\my\\windows\\path";

// should be:
import type { MyType } from "../my/windows/path";
```

Rust and typescript are smart enough to handle unix paths, and the difference creates some noise when working across windows and os x environments. Note: I believe this only happens when the dependency includes "..". It seems like there's a migration to a new path api in the works, so that might address this.

**Comment by NyxCode** [comment]
Thanks for opening an issue for this.   
I've been aware of this, but since it doesn't break anything & Windows use is pretty rare this hasn't been fixed yet.  
I do agree though - the generated files should be reproducible across platforms.
