### ISSUE TITLE
[Feature] export to single file?

### ISSUE THREAD

**Issue by boan-anbo** [Aleph-Alpha/ts-rs#35]
Is it possible to add for nested structs like

```
struct Player {
    role: Role
}
```
the feature to export to one file like
```
export! {
    [Role, Player] => "player.ts",
}
```

Then it's a single file and ready to use after generation without needing to manually add `import` statements. 

Great project btw!

**Comment by NyxCode** [comment]
Oh, we need to add this to the example! Yes, its possible. The syntax is
```rust
export! {
    Role, Player => "player.ts",
}
```

**Comment by NyxCode** [comment]
They don't have to be nested either, you can export whatever structs you like into one typescript file

**Comment by NyxCode** [comment]
However, the import statements should be automatically generated, as long as you do it in the same call to `export`:
```rust
export! {
    Role => "role.ts", 
    Player => "player.ts",
}
```
this should generate an import on Role in player.ts

**Comment by boan-anbo** [comment]
Thanks a lot! It works great!

**Comment by thorlucas** [comment]
I don't see this macro in the docs?

**Comment by NyxCode** [comment]
Version 6 removed the export! macro, replacing it with #[ts(export)]. If you want to know more, take a look at the release notes.
