### ISSUE TITLE
Feature request: multiple concrete

### ISSUE THREAD

**Issue by loikki** [Aleph-Alpha/ts-rs#355]
Hi,

Thanks for this crate. It helps a lot :)

**Is your feature request related to a problem? Please describe.**
I have a generic structure  (2 parameters with multiple traits and one depending on the other) and it looks like the derive instruction does not work properly. The dummy  structure is lacking some traits: ```the trait `for<'sa> Deserialize<'sa>` is not implemented for `Dummy`, which is required by `SecondaryAttribute<Dummy, Dummy>: TS```

**Describe the solution you'd like**
If I concretize the structure, this error is easily solved. Unfortunately, from what I understood, it can be only done once. Could it be possible to allow multiple concrete instructions? I guess it would require an additional keyword in order to give a name to this concretization.

For example:
```rust
#[derive(TS)]
#[ts(concretize(T=i32, rename="MyI32"))]
#[ts(concretize(T=i64, rename="MyI64"))]
struct MyStruct<T>
where T: Deserialize + Serialize
{
  value: T
}
```

**Describe alternatives you've considered**
I tried implementing myself the trait but it looks like a lot of work for such "common" issue.

Another possibility would be to have an instruction to define which trait should be derived but it would fail as soon as someone needs a trait that does not come from a macro:
```rust
#[derive(TS)]
#[ts(derive="Deserialize,Serialize")]
struct MyStruct<T>
where T: Deserialize + Serialize
{
  value: T
}
```

**Comment by loikki** [comment]
Hi,

Thanks for the fast answer and the suggestion. With serde, the instruction `deserialize_with` seems a bit messy with my code structure. It forced me to restrict the type during the definition of the struct.

I will simply release a new major version and drop the support for the old API and thus won't need `deserialize_with` anymore. Sorry for the noise.

Best,

**Comment by NyxCode** [comment]
no problem, always happy to help!
