### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gschier** [Aleph-Alpha/ts-rs#356]
#316 was merged back in May but not yet released (according to [CHANGELOG.md](https://github.com/Aleph-Alpha/ts-rs/blob/main/CHANGELOG.md)). Can we get a new release for this? 

It's getting painful to re-export 70+ types.

![CleanShot 2024-09-17 at 10 25 49@2x](https://github.com/user-attachments/assets/ec9981e5-38c8-4089-b6af-2a7d03cc6baf)

**Comment by gschier** [comment]
For context, I would love to configure it in `build.rs` like this:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rustc-env=TS_RS_EXPORT_DIR=../../plugin-runtime-types/src/gen/index.ts");

    Ok(())
}
```

**Comment by Chaoses-Ib** [comment]
For #316, you can directly use the git repository as a workaround:
```toml
ts-rs = { version = "9.0.1", git = "https://github.com/Aleph-Alpha/ts-rs.git", rev = "9763ca019509fa4bbbfbaada1ad105c7192dee0b" }
```

For `TS_RS_EXPORT_FILE`, another TS generator [tsync](https://github.com/Wulf/tsync) can do this. Though it's not actively maintained and has several problems.

**Comment by gustavo-shigueo** [comment]
> #316 was merged back in May

Not quite. It was opened in may, but the merge happened in August 1st

Also, I think you mean `TS_RS_EXPORT_DIR` and the command you'd need is `TS_RS_EXPORT_DIR=../../plugin-runtime-types/src/gen/index.ts cargo test`

Using this, together with the change to `Cargo.toml` suggested by @Chaoses-Ib, your types should all be exported to your index file

**Comment by gschier** [comment]
@gustavo-shigueo setting `TS_RS_EXPORT_DIR=../../plugin-runtime-types/src/gen/index.ts` simply creates a directory called `index.ts` and puts the individual files there.
