### ISSUE TITLE
Update README.md with struct compilation from Rust to Typescript example

### ISSUE THREAD

**Issue by monstaflame** [Aleph-Alpha/ts-rs#361]
I've just discovered this nice crate. There is one thing that made me pause, there is no example of Typescript that the crate would generate.

My suggestion / request is adding the example below in the `README.md` (I'm taking the current content of the section and add what I would like to add) :

>```rs
>use ts_rs::TS;
>
>#[derive(TS)]
>#[ts(export)]
>struct User {
>    user_id: i32,
>    first_name: String,
>    last_name: String,
>}
>```
>
>When running `cargo test`, the TypeScript bindings will be exported to the file `bindings/User.ts`.
>
>```ts
>interface User {
>    userId: number,
>    firstName: string,
>    lastName: string,
>}
>```

Something like that.

**Comment by NyxCode** [comment]
Maybe we can commit the bindings generated by the example?

**Comment by monstaflame** [comment]
Yes it would be great !
