### ISSUE TITLE
bug: Regression Empty Struct Enum Variants with serde tag attribute

### ISSUE THREAD

**Issue by newcomertv** [Aleph-Alpha/ts-rs#369]
**Describe the bug**
Attempting to derive TS for an enum containing empty structs as well as the serde tag attribute fails.

This bug is a regression from v9.1

**Expected behavior**
The code should compile

**Version**
v10.0

**Additional context**
Not Applicable

**Comment by gustavo-shigueo** [comment]
Hello @newcomertv, can you provide us with a code sample to help us reproduce the issue?

**Comment by gustavo-shigueo** [comment]
I believe I found the issue, The `struct_def` function decides whether to call `named` or `empty_object` in the case of a struct variant by checking only the number of fields (This was done to prevent `type Foo = { }`, which is a big mistake in TS), but if the `tag` attribute is present, it should always call `named` as it will add a new field to the struct, making sure it won't be an empty type
