### ISSUE TITLE
Feature request: Override Serde tags if TS ones are provided

### ISSUE THREAD

**Issue by gluax** [Aleph-Alpha/ts-rs#375]
**Is your feature request related to a problem? Please describe.**
Hi, I'm using this crate via the [qubit](https://github.com/andogq/qubit), which has `ts-rs` with default features enabled.
I describe the issue [here](https://github.com/andogq/qubit/issues/91), but I think it might be nicer to have this crate support the behavior instead. Unless it does, and `qubit` is doing something under the hood to prevent this?

**Describe the solution you'd like**
Even with the serde feature enabled it would be nice if the `ts` tag could overwrite the `serde` tag.
For example:
```rust
#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[serde(rename_all = "snake_case")]
#[ts(rename_all = "camelCase")]
pub struct PubkeyParams {
    pub activation_delay:       String,
    pub activation_threshold_percent: u8,
}
```

This would be nice in cases where on the rust side I'm fetching data, and then sending it to the typescript side. Where the latter the linter yells at me for not using camel case.

**Describe alternatives you've considered**
I'm not sure. This could be done with the `serde-compat` feature disabled I imagine? But that might have other awkward implications. 

**Additional context**
I'm being a bit concise here, because most of my information is in the linked issue on qubit.

**Comment by gustavo-shigueo** [comment]
It would indeed make sense for `ts-rs` to give the `ts` attribute precedence over `serde`, but beware that if you use `serde` to send your rust data to ts and you have different `rename_all` values between the two, you will have type safety problems, as TypeScript will think the type's property names are `camelCase`, but `serde` will be sending `snake_case` data

**Comment by gustavo-shigueo** [comment]
Also of note, I just looked at the code and wrote a test, and ts-rs does in fact do this, the `ts` attribute overrides the `serde` attribute, I think the problem you have is with your serialization logic. Remember, `ts-rs` only generates type declarations for your TS code, it does not actually serialize data.

If you serde serialization is sending `snake_case` data and your type declarations are expecting `camelCase` cata you will have problems.

Consider using the following `serde` attribute instead:
`#[serde(rename_all(serialize = "camelCase", deserialize = "snake_case"))]`

This will make serde send `camelCase` data to your TS code, but it will still expect to receive `snake_case` data to deserialize if that is what your rust code is receiving

Also consider just making the `ts` and `serde` `rename_all` match, (i.e. set both to the same value - usually `camelCase`), that will solve your problem and make your code simpler

**Comment by gluax** [comment]
Yea it already does as you described.

I sadly cannot have them aligned as I explained. The rust calls an API which gets the JSON in snake case.

Our ts side the lints and complains that it is snake case.

For some of the types I may be able to do deserialize from snake case and serialize to camel case though.

If any types go back and forth in the TS side, I may have to make a clone of the type.
