### ISSUE TITLE
Alternative representation for empty structs

### ISSUE THREAD

**Issue by Palmik** [Aleph-Alpha/ts-rs#39]
Currently empty structs are represented as `type Foo = null`. A reasonable alternative would be `interface Foo = {}`.

**Comment by NyxCode** [comment]
Agreed. I do think that we need some *good* way of letting users configure what they want. I'll start looking into how to support a configuration file for the derive macro. Then, I'm open to these kinds of customizations.

**Comment by thorlucas** [comment]
I think they should be represented as `type Foo = 'foo'` as this is a common idiom at least in my work. It allows you to define tags in a way that's only defined in one place. I.e. then you can do like,

```ts
type Foo = 'foo';
type Bar = 'bar';
type Baz = 'baz';

type All = Foo | Bar | Baz;

type X = Extract<All, Foo>;
```

**Comment by NyxCode** [comment]
Closing this for now - the default bindings for unit structs are now compatible with the output of serde_json. If something else is desired, overrides should be used.
