### ISSUE TITLE
Empty structs with braces lead to compile error.

### ISSUE THREAD

**Issue by Palmik** [Aleph-Alpha/ts-rs#40]
Example:

```rust
#[derive(ts_rs::TS)]
struct Foo {}
```

Compile error:
```
cannot infer type for type parameter `T`
```

Note that empty structs without braces work.

**Comment by NyxCode** [comment]
fixed on master

**Comment by harrysolovay** [comment]
I'm getting this issue as well (currently working with `6.0.2`)

**Comment by NyxCode** [comment]
> I'm getting this issue as well (currently working with `6.0.2`)

Are you sure?  
We do have [this test](https://github.com/Aleph-Alpha/ts-rs/blob/main/ts-rs/tests/unit.rs) in place, which does pass:

**Comment by harrysolovay** [comment]
Unfortunately yes :/

<img width="923" alt="Screen Shot 2021-11-14 at 4 07 42 PM" src="https://user-images.githubusercontent.com/4893548/141698650-e041aafc-99cd-45f7-9d93-6dad8fd463ad.png">

Please let me know what other information I can provide to help with diagnosis.

**Comment by NyxCode** [comment]
Ahh! That's an empty enum, not a unit struct. 
That is indeed not yet supported. I would say this should generate
```ts
type PortableForm = never;
```

**Comment by harrysolovay** [comment]
Good catch––sorry I missed that. Should have opened as a new issue.

And yea, the never type seems fitting.

**Comment by NyxCode** [comment]
fixed in 6.0.3 :wink: 
https://github.com/Aleph-Alpha/ts-rs/blob/6cb2b359186887ea30a94d4cc4697d27a69381e4/ts-rs/tests/union.rs#L14-L23

**Comment by NyxCode** [comment]
we *could* do even more, for example generating `type SomeType = never` for every interface which contains `never`, but I feel like that's a bit out of scope.

**Comment by NyxCode** [comment]
eh sorry, 6.0.4

**Comment by harrysolovay** [comment]
You're on a roll today! Thank you @NyxCode!
