### ISSUE TITLE
Generate `import type ..` where possible

### ISSUE THREAD

**Issue by Palmik** [Aleph-Alpha/ts-rs#41]
The automatic imports should be `import type { Foo } from ...`, otherwise strict typescript settings will cause the following error: `import is never used as a value`.

**Comment by NyxCode** [comment]
I would like to support the ability to support both. An appropriate method in the `TS` trait could indicate whether `import ..` or `import type ..` should be emitted. While this might now be used immediately, it'd be great if users could decide wheather to export an interface or a concrete type like an enum in the future.

**Comment by NyxCode** [comment]
implemented in 6.0.0
