### ISSUE TITLE
Is there a reason why i64 and u64 uses number instead of bigint?

### ISSUE THREAD

**Issue by BlueGreenMagick** [Aleph-Alpha/ts-rs#42]
rust's `i64::MAX == 9223372036854775807`(2^63 - 1) while in javascript `Number.MAX_SAFE_INTEGER == 9007199254740991` (2^53 - 1)

But in this library, only `i128` and `u128` is defined using `BigInt`. So I was wondering if there was some reasoning behind the decision.

**Comment by NyxCode** [comment]
fixed on master
