### ISSUE TITLE
Generics dropped for newtype structs in 4.x

### ISSUE THREAD

**Issue by Heliozoa** [Aleph-Alpha/ts-rs#45]
Hi,
I noticed that the struct
```rust
#[derive(ts_rs::TS)]
struct Wrapper(Vec<String>);
```
results in
```ts
export type Wrapper = Array;
```
in 4.x. In 3.x the result was
```ts
export type Wrapper = string[];
```
I think the issue is the same as in https://github.com/Aleph-Alpha/ts-rs/issues/32#issuecomment-930175550, which is to say there's no method to call that will return `Array<string>` that we could use at https://github.com/Aleph-Alpha/ts-rs/blob/5e299d6266a33e366560d2dd08051b57bb104457/macros/src/types/newtype.rs#L39. It would be possible to patch it up by handling the generics for newtypes specifically, but I think that'd break again if you tried `struct Wrapper(Vec<Vec<String>>)`.

**Comment by NyxCode** [comment]
I don't think this is related to #32. This should be possible to fix by just properly handling generics for newtypes. I'll look into it.

**Comment by NyxCode** [comment]
This is fixed on the current master.
[these tests](https://github.com/Aleph-Alpha/ts-rs/blob/main/ts-rs/tests/generic_fields.rs) now pass.
