### ISSUE TITLE
Derive from newtype wrapper

### ISSUE THREAD

**Issue by thought2** [Aleph-Alpha/ts-rs#49]
It seems to be possible to derive e.g. serde's `Serialize` trait from a (newtype wrapper)[https://doc.rust-lang.org/book/ch19-04-advanced-types.html] around a struct which itself does not implement this trait.
I tried to do the same with deriving the `TS` trait from this library. And in this case the compiler seems to complain about a missing trait on the wrapped type.

Is there anything we can do to make this work?

**Comment by NyxCode** [comment]
im not entitely sure what you mean. could you elaborate a bit?

**Comment by NyxCode** [comment]
If I understood this right, then no, that doesn't work, and it doesn't work with serde either.
If I didn't, please let me know.
