### ISSUE TITLE
export type aliases

### ISSUE THREAD

**Issue by dakom** [Aleph-Alpha/ts-rs#51]
this would be great, so if I have `type Foo = String` in Rust, and I use `Foo`, it will also be `Foo` on the TS side

**Comment by NyxCode** [comment]
I'm afraid we cannot support this.  
`ts-rs` takes advantage of rusts type resolution. In rust, however, a type alias is completely transparent. If you had  
```rust
type X = i32;
struct Y { x: X }
```
then ts-rs would have no way of telling that `X::x` is refering to a type alias - internally, the implementation of `<Y as TS>::decl()` would call `<X as TS>::decl()`, which is just an alias to `<i32 as TS>::decl()`. 
You could declare the type alias in TS yourself and use `#[ts(type = "YourAlias")]` or just use a newtype like this: 
```rust
#[derive(TS)]
struct Foo(String);

// generates `type Foo = string`
```

**Comment by wtachau** [comment]
Using a transparent struct as described above solved the trick for me. Might be worth a note in the README.

**Comment by Victor-N-Suadicani** [comment]
For anyone else who searched and found this: If you already have a type alias and you want to export it, you can also do this:

```rust
type MyAlias = Vec<u32>;

#[derive(TS)]
#[ts(rename = "MyAlias", export)]
pub struct ExportMyAlias(pub MyAlias);
```
