### ISSUE TITLE
export cargo docs as tsdoc

### ISSUE THREAD

**Issue by dakom** [Aleph-Alpha/ts-rs#52]
this might be too big of an ask... but would be cool =)

**Comment by NyxCode** [comment]
actually, doc comments (`/// something`) are just syntactic sugar for `#[doc]`: https://doc.rust-lang.org/rustdoc/the-doc-attribute.html
If you feel like it, feel free to open a PR. Always happy to help if you've got questions.

**Comment by riellyd** [comment]
Are there any plans to retain any kind of comments?  It helps the front end dev workflow when you don't have to look up the rust type to read any comments about usage, particularly when the files do not site adjacent to one another.  Thanks!

**Comment by NyxCode** [comment]
> Are there any plans to retain any kind of comments? It helps the front end dev workflow when you don't have to look up the rust type to read any comments about usage, particularly when the files do not site adjacent to one another. Thanks!

I'd like to implement this feature. I'm currently a bit busy, so If you feel like it, open a PR.  
We can only retain doc comments, since normal comments are stripped before proc macros are run.

**Comment by riellyd** [comment]
Would love to help, but sadly I am in the same boat as you - rather busy right now. Also, have only done basic proc macros a while ago so would be slow going for me.  Perhaps when things are a bit quieter I'll take a stab if nobody else gets round to doing it, would be a nice feature to have for bigger projects.

**Comment by escritorio-gustavo** [comment]
Closing this issue in favor of tracking it through #188
