### ISSUE TITLE
Parse error stemming from default type param

### ISSUE THREAD

**Issue by harrysolovay** [Aleph-Alpha/ts-rs#55]
I'm currently trying to apply the `TS` derive to the following:

```diff
#[derive(Clone, PartialEq, Eq, Encode)]
- #[cfg_attr(feature = "std", derive(Decode, Serialize, Debug))]
+ #[cfg_attr(feature = "std", derive(Decode, Serialize, Debug, TS))]
#[cfg_attr(
	feature = "std",
	serde(bound(serialize = "T::Type: Serialize, T::String: Serialize"))
)]
pub struct StorageEntryMetadata<T: Form = MetaForm> {
	pub name: T::String,
	pub modifier: StorageEntryModifier,
	pub ty: StorageEntryType<T>,
	pub default: Vec<u8>,
	pub docs: Vec<T::String>,
}
```

The resulting error points to the `=` token:

```
expected one of `(`, `+`, `,`, `::`, `<`, or `>`, found `=`
```

Any advice on getting this working would be greatly appreciated. Thank you!

**Comment by NyxCode** [comment]
Thanks for the report! My guess is that default generic arguments are not handled correctly. Will take a look at it tonight.

**Comment by harrysolovay** [comment]
Thank you!!!

**Comment by NyxCode** [comment]
This should be fixed on master & version 6.0.1 which I just released.  
There are still some holes in the support for generics (#56), but this should work now (at least my test passes now :D)

**Comment by harrysolovay** [comment]
I'll try it out later today. Thank you so much @NyxCode!

**Comment by NyxCode** [comment]
No problem - again thanks for opening an issue. It's incredible how many edge cases there are which I just did not think about.  

I also fixed #57, so now `struct X<Y = String> { .. }` properly generates `interface X<Y = string> { .. }`

**Comment by harrysolovay** [comment]
Apologies for overloading you with issues.

After applying the derive to my struct (which includes the newly-supported default type param)...

<img width="1105" alt="Screen Shot 2021-11-14 at 4 46 40 PM" src="https://user-images.githubusercontent.com/4893548/141699882-38073ebe-15d5-4c71-985a-b51b36a0868c.png">

When I add the crate-level `#![feature(associated_type_bounds)]`, the error turns into yet another:
<img width="766" alt="Screen Shot 2021-11-14 at 4 44 45 PM" src="https://user-images.githubusercontent.com/4893548/141699916-6358f973-3bbe-4ff0-a4a0-a46819067e92.png">

Any recommendations?

**Comment by NyxCode** [comment]
> Apologies for overloading you with issues.

no worries.   

Will take a look at it. Seems like a related issue - We generate an `impl TS for YourType` item, but getting the generics of that right is not super trivial.

**Comment by NyxCode** [comment]
@harrysolovay 
A fix, [test](https://github.com/Aleph-Alpha/ts-rs/blob/1bc1450057d02136f8e794fd59f33ff254501f1b/ts-rs/tests/generics.rs#L185-L214) and release of 6.0.5 later, this should now work.
Please let me know if you hit yet another issue!

**Comment by harrysolovay** [comment]
It's looking good! Thank you!!!
