### ISSUE TITLE
Allow any fallback type

### ISSUE THREAD

**Issue by theduke** [Aleph-Alpha/ts-rs#68]
Sometimes it might not be possible or desirable to generate full typings, eg when using third party definitions.

It would be great to have a `#[ts(any)]` attribute that will just generate defintions with `any`.

Should be available on struct fields and and variants.

**Comment by NyxCode** [comment]
Currently, you can do this with `#[ts(type = "any")]`. While `#[ts(any)]` is more concise, I don't think we should add an other attribute just for that.

**Comment by theduke** [comment]
Ah, `#[ts(type = "any")]` is perfectly fine.
