### ISSUE TITLE
Serde custom crate support

### ISSUE THREAD

**Issue by sinnrrr** [Aleph-Alpha/ts-rs#69]
Hey! I've encountered the issue, that due to `ts-rs` does not support the serde `crate` feature, the program fails to compile.

Here is an example:
```
#[derive(BorshDeserialize, BorshSerialize, Serialize, Deserialize, TS)]
#[serde(crate = "near_sdk::serde")]
#[ts(export)]
pub struct SomeStruct {
    pub someProperty: Option<Base64VecU8>,
}
```

Error:
```
warning: failed to parse serde attribute
  | 
  | 
  | #[serde(crate = "near_sdk::serde")]
  | #[serde(crate = "near_sdk::serde")]
  | 
  = note: ts-rs failed to parse this attribute. It will be ignored.

error[E0277]: the trait bound `near_sdk::json_types::Base64VecU8: ts_rs::TS` is not satisfied
```

Thanks!

**Comment by NyxCode** [comment]
What I think is going on here is much more mundane - Base64VecU8 just doesn't implement `ts_rs::TS`. You should try wrapping it in a newtype and implementing `ts_rs::TS` for that yourself, or use `#[ts(type = "some typescript type")]` to manually set the type of the field.

**Comment by sinnrrr** [comment]
Thanks, @NyxCode! That did work, sorry for such a stupid issue.

**Comment by NyxCode** [comment]
absolutely no problem. feel free to open an other one if you hit an other issue.
