### ISSUE TITLE
Support TS for Range, RangeInclusive, Path, PathBuf

### ISSUE THREAD

**Issue by HalfVoxel** [Aleph-Alpha/ts-rs#75]
Most types are already covered by ts-rs, but the stdlib contains a few more ones that would be useful to have.

This is a list of what is included in serde by default, it would probably make sense to support most of these in ts-rs as well: https://docs.rs/serde/latest/serde/ser/index.html

**Comment by NyxCode** [comment]
Fixed in 6.1.1

**Comment by HalfVoxel** [comment]
Thanks! :D
