### ISSUE TITLE
Is there a way to export external types?

### ISSUE THREAD

**Issue by Roryl-c** [Aleph-Alpha/ts-rs#82]
I am using an [external library](https://crates.io/crates/twilight-model) which provides numerous models. I'd like to export a few of them that I'm returning from an API. The docs suggest this:
> If there's a type you're dealing with which doesn't implement TS, use #[ts(type = "..")] or open a PR.  

so I attempted to use the attribute like this: `#[ts(type = "TypeNameHere")]` but this just exports a type alias to `TypeNameHere` instead of the the struct itself.

Is there any way to have ts-rs export external types in their entirety?

**Comment by NyxCode** [comment]
Sadly, no. It's just like you're plain out of luck when an external library doesn't implement `serde::Serialize` or some other trait.  
You can use `#[ty(type = "TypeNameHere")]` and write the typescript bindings for the type in question yourself and put it in an ambiant typescript file (`some-file.d.ts`).

**Comment by NyxCode** [comment]
If it's a simple type, like let's say `{ x: number, y: number }`, you can also just do `#[ts(type = "{ x: number, y: number, }")]`

**Comment by Roryl-c** [comment]
Dang, oh well. Thanks for the response and suggestions.

**Comment by OliverEvans96** [comment]
> It's just like you're plain out of luck when an external library doesn't implement `serde::Serialize` or some other trait.

How about when the external library _does_ implement `serde::Serialize`, but not `ts_rs::TS`?

**Comment by Roryl-c** [comment]
@OliverEvans96 They were comparing the two situations, not saying that `serde::Serialize` can be used to export external types.

If `serde::Serialize` or another trait you need is not implemented on an external type, you're [pretty much out of luck](https://serde.rs/remote-derive.html). The same is true for `ts_rs::TS`. The only thing there is to do is create new types wrapping or copying the external ones that implement the trait you need.
