### ISSUE TITLE
TS is implemented for many wrapper types, but not Mutex

### ISSUE THREAD

**Issue by Brendonovich** [Aleph-Alpha/ts-rs#85]
Serde implements Serialize/Deserialize for Mutexes by default, wouldn't it make sense to do the same here? I'd imagine it should just pass through the generic type it contains like Arc.

**Comment by Brendonovich** [comment]
It also isn't implemented for `Weak` Arcs

**Comment by NyxCode** [comment]
now implemented, thanks for opening the issue
