### ISSUE TITLE
Reuse ts exports in interface extends

### ISSUE THREAD

**Issue by Roms1383** [Aleph-Alpha/ts-rs#87]
Hey hi!
I came up with an idea that I won't have time to look further into sadly,
but that I thought worth sharing.

It's about reusing `#[ts(export)]` in nested struct to provide `interface extends ...` on TypeScript side.
Also, a struct which would solely contain nested `#[ts(exported)]`ed structs could use TypeScript [intersection types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#intersection-types).

---

I think it's better illustrated with an example, so imagine:
In the codebase one would have, e.g.

```rust
#[derive(Serialize, Debug, Deserialize, TS)]
#[ts(export)]
pub struct CreatedAt {
    pub created_at: DateTime<Utc>,
}

#[derive(Serialize, Debug, Deserialize, TS)]
#[ts(export)]
pub struct Shop {
    pub specific: String,
    #[serde(flatten)]
    pub created_at: CreatedAt,
}
```

I noticed here that if all fields of `Shop` are `#[ts(skip)]` it doesn't compile, while I would assume getting an empty interface in TypeScript, but this is not a big deal in my case.

What one might ideally want to get generated is the following:
![code001](https://user-images.githubusercontent.com/21016014/155651971-e19a89be-91f2-4096-9923-9610189940eb.png)

But instead will currently get:
![code002](https://user-images.githubusercontent.com/21016014/155651956-b112af47-5de2-4c93-b917-667df688c09e.png)

I don't know if it makes sense, since I haven't found any similar opened or closed issue.
It's just that usually `interface` inheritance and _intersection types_ (e.g. `pub type Shop = CreatedAt & Uuid & SomeOtherInfos`)
are common practice in TypeScript world.

---

Another point that was a bit confusing to me is:
```rust
#[derive(Debug, Deserialize, Serialize, TS)]
#[ts(export_to = "bindings/commons.ts")]
pub struct A { pub field: String }

#[derive(Debug, Deserialize, Serialize, TS)]
#[ts(export_to = "bindings/commons.ts")]
pub struct B { pub field: String }
```
I would assume that it would generate:
```ts
// bindings/common.ts
export interface A { field: string, }
export interface B { field: string, }
```
Instead, currently each call to the macro will override previous definition(s) in the destination file.

---

Thanks for your time reading through all this, it's a bit long 😅

**Comment by escritorio-gustavo** [comment]
We are changing the code to use `type`s instead of interfaces so this is unlikely to be implemented, though not impossible, as the type intersection operator pretty much does the same as `extends`

**Comment by escritorio-gustavo** [comment]
Still... this could make the `flatten` attribute simpler

**Comment by escritorio-gustavo** [comment]
This issue massively helped introduce enum flattening by giving me the idea of using type intersections for all flattening operations, but I don't see much of a reason to implement it as described.

It would indeed make nicer TS code, but said code is auto generated, so you won't have to maintain it yourself and your LSP's intellisense will guide you through the properties of the object
