### ISSUE TITLE
Add option to export Vec<Type> as Type[] instead of Array<Type>

### ISSUE THREAD

**Issue by AdamKuziemski** [Aleph-Alpha/ts-rs#93]
Would it be possible to export `Vec<T>` as `T[]` instead of `Array<T>`?

Example code:
```rust
#[derive(TS, Serialize)]
#[ts(export)]
pub struct SomeChoresStruct {
    pub chores: HashMap<String, Vec<Chore>>,
    pub extra_chores: Vec<Chore>
}
```
Currently this code produces:
```typescript
export interface SomeChoresStruct {
  chores: Record<string, Array<Chore>>;
  extra_chores: Array<Chore>;
}
```
In my project, I'm sticking to the `Type[]` format instead so it would be nice if it got exported as:
```typescript
export interface SomeChoresStruct {
  chores: Record<string, Chore[]>;
  extra_chores: Chore[];
}
```

**Comment by NyxCode** [comment]
This is just a syntactic difference, but `T[]` is the same as `Array<T>` in TS. I would suggest you try using a seperate formatting tool if you really need it to be `T[]`
